# Generated by Django 5.1.4 on 2025-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_personalite_nombre_personalite_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('INSERT', 'Insertar'), ('DELETE', 'Eliminar'), ('UPDATE', 'Actualizar')], max_length=10)),
                ('tabla', models.CharField(max_length=100)),
                ('descripcion', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
